interpro.api.base-url=https://www.ebi.ac.uk/interpro/api
interpro.matches.base-url=https://www.ebi.ac.uk/interpro/matches/api
ebisearch.base-url=https://www.ebi.ac.uk/ebisearch/ws/rest
interproscan.base-url=https://www.ebi.ac.uk/Tools/services/rest/iprscan6

interproscan.email=interpro-mcp-prod@ebi.ac.uk